### ISSUE TITLE
Issue - Flycheck checker elixir returned non-zero exit code 1, but its output contained no errors

### ISSUE THREAD

**Issue by anildigital** [lbolla/emacs-flycheck-elixir#5]
```
Try installing a more recent version of elixir, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker elixir: Flycheck checker elixir returned non-zero exit code 1, but its output contained no errors: 
== Compilation error on file flycheck_config.exs ==
** (exit) exited in: GenServer.call(Mix.State, {:get, {Map, :get, [:env, :dev]}}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
    flycheck_config.exs:27: (file)
    (elixir) lib/kernel/parallel_compiler.ex:115: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1


Try installing a more recent version of elixir, and please open a bug report if the issue persists in the latest release.  Thanks!
user-error: Minibuffer window is not active
```

I constantly see this while editing Elixir projects in Emacs. How to get rid of this error? Thanks.

**Comment by lbolla** [comment]
I don't recognize the file "flycheck_config.exs". What flycheck-elixir package are you using?

**Comment by anildigital** [comment]
I am getting below error now. (This happens whenver I try to save `.ex` file)

I am using flycheck-elixir-20160629.59 with "GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-13"

```
Try installing a more recent version of elixir, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker elixir: Flycheck checker elixir returned non-zero exit code 1, but its output contained no errors: 
== Compilation error in file flycheck_mix.exs ==
** (exit) exited in: GenServer.call(Mix.State, {:get, {Map, :get, [:env, :dev]}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:760: GenServer.call/3
    flycheck_mix.exs:9: Todolist.MixProject.project/0
    lib/mix/project.ex:642: Mix.Project.get_project_config/1
    lib/mix/project.ex:113: Mix.Project.push/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

Try installing a more recent version of elixir, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by lbolla** [comment]
I think this issue is related to #1
